name: Build PX4 SITL for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout PX4 repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install prerequisites
        run: |
          choco install ninja cmake git python3 --no-progress -y

      - name: Build PX4 SITL
        shell: bash
        run: |
          git submodule update --init --recursive
          make px4_sitl_default

      - name: Upload px4.exe
        uses: actions/upload-artifact@v4
        with:
          name: px4-sitl-windows
          path: build/px4_sitl_default/bin/px4.exe
